name: Build and archive library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: ./gradlew build
      
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/spnego-jakartaee-0.10.0.jar